theme: jekyll-theme-cayman


title: "直接捐款公示平台"

repo: "https://github.com/yabaowang/yabaowang.github.io.git"

google_analytics: UA-155170936-2

#count total number of visitors
visitor_count: 3364
visitor_count_timestamp: Feb 25, 16:00PM


github:
  is_project_page: false

  
